Merge branch 'fix/basename-4' into 'development'
chatch/stellarexplorer pull request #331
Opened 2021-10-13 09:18 UTC by ee-ehab-xx

Merge branch 'fix/basename-4' into 'development'

2021-10-13 17:20 UTC, zoli18153 commented
minden jót mindenkinek

2021-10-14 12:31 UTC, Traihoha commented
Ok

2021-10-15 02:34 UTC, Macfred11 commented
Good job

2021-10-16 09:12 UTC, Fitrah81 commented
Test

2021-11-01 05:39 UTC, congho1804 commented
> Merge branch 'fix/basename-4' into 'development'

2021-12-02 20:34 UTC, anilk666 commented
> Merge branch 'fix/basename-4' into 'development'

Ok

2021-12-02 20:36 UTC, anilk666 requested changes

2021-12-02 20:36 UTC, anilk666 commented on src/components/Account.js
>          type={bal.asset_type}
I will give you 100

2021-12-09 06:39 UTC, Isaibrahim71998 reviewed
Is mostly be an wallet or account no to pay

2021-12-18 06:33 UTC, Slyman042 commented
> Merge branch 'fix/basename-4' into 'development'

Superb

2021-12-18 06:33 UTC, Slyman042 commented
Waooo

2021-12-18 17:00 UTC, Olcay222 commented
GABD5PVZZO44UOXXPRTG3Q5KPCHXBDKLFA6VD4UDD5NUMJYVG54M7ZWS

2021-12-18 17:01 UTC, Olcay222 commented
@wwolcayto@gmail.com

2021-12-18 17:01 UTC, Olcay222 commented
Olcay 222

2021-12-18 18:44 UTC, Jessicadrichardson commented
Ok

2021-12-31 01:54 UTC, Anne0506 approved these changes

2022-01-04 03:54 UTC, Hariommeena123 commented
Kab tak Dal na h pesa Lena h ke nih aaap ko

2022-02-03 11:57 UTC, Kittykat72766 approved these changes

2022-02-03 11:58 UTC, Kittykat72766 approved these changes

2022-02-25 17:05 UTC, Ahmedjamal66 approved these changes

2022-04-23 20:13 UTC, Robin8004 approved these changes

2022-04-23 20:14 UTC, Robin8004 approved these changes

2022-04-23 20:15 UTC, Robin8004 approved these changes

2022-04-23 20:16 UTC, Robin8004 approved these changes

2022-04-23 20:19 UTC, Robin8004 approved these changes

2022-04-23 20:21 UTC, Robin8004 approved these changes

2022-04-23 20:22 UTC, Robin8004 approved these changes

2022-04-23 20:33 UTC, Robin8004 commented
> Is mostly be an wallet or account no to pay

Tnx

2022-04-23 22:52 UTC, Robin8004 approved these changes

2022-04-25 18:38 UTC, DevinAPieceOfSit reviewed
@noxious

2022-04-26 04:44 UTC, Robin8004 approved these changes

2022-04-26 04:46 UTC, Robin8004 approved these changes

2022-05-02 22:02 UTC, Robin8004 approved these changes
Ok

2022-05-13 02:10 UTC, DevinAPieceOfSit approved these changes
pi-apps:development FR:@noxious15

2022-05-25 21:56 UTC, christiannolia approved these changes

2022-06-06 21:11 UTC, 077258200 commented
[C704FF9BA82C511B4A4C4767C66A610C71CB37F2511217CC5A3C59DFF2FE906DJSON](2$) 

> 

> ``

2022-06-11 06:14 UTC, Rickm6045 commented
Hello

2022-06-11 12:45 UTC, FukYaMudda approved these changes

2022-07-04 15:38 UTC, RRAAJJUUDDAASS commented
![1591116269327](https://user-images.githubusercontent.com/108684068/177185669-8abb4bcb-9d0b-42d9-b70a-b6dfe11717c8.jpg)
RRAAJUUDDAASS

2022-07-25 22:25 UTC, Asijoon commented
Hello good time 
in the browser Do you include the Persian language translator?
There was more or less in the Pii Ke program, Search and Escape
Please post here too. The number of Iranian users is not small
Thank you

2022-07-27 02:56 UTC, Thienan007 reviewed
![Screenshot_2022-07-16-21-17-28-89](https://user-images.githubusercontent.com/105554274/181150931-767f72dd-55cd-4942-bd01-5d198f2e9855.png)

2022-07-27 03:13 UTC, Thienan007 reviewed
![Screenshot_2022-07-16-21-17-28-89](https://user-images.githubusercontent.com/105554274/181150931-767f72dd-55cd-4942-bd01-5d198f2e9855.png)

2022-08-08 03:11 UTC, janbic1822 approved these changes

2022-08-08 09:21 UTC, Thienan007 commented
Ok

2022-08-09 18:56 UTC, Ilyasmalik7788 commented
Yes

On Mon, Aug 8, 2022, 8:11 AM Bicbic Alib Madali ***@***.***>
wrote:

> ***@***.**** approved this pull request.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/chatch/stellarexplorer/pull/331#pullrequestreview-1064549995>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AUVCQZDAQA4EKT2G5KQJIADVYB3FZANCNFSM5F4WB6YA>
> .
> You are receiving this because you are subscribed to this thread.Message
> ID: ***@***.***>
>

2022-08-09 18:57 UTC, Ilyasmalik7788 commented
Yes

On Mon, Aug 8, 2022, 2:21 PM Thienan007 ***@***.***> wrote:

> Ok
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/chatch/stellarexplorer/pull/331#issuecomment-1207877721>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AUVCQZATTGYBQOVJAJ4IWFTVYDGSHANCNFSM5F4WB6YA>
> .
> You are receiving this because you are subscribed to this thread.Message
> ID: ***@***.***>
>

2022-08-12 05:40 UTC, Thienan007 commented
Ok

2022-08-12 05:43 UTC, Thienan007 reviewed
Ok

2022-08-13 14:11 UTC, Asahan63 commented
Go...

2022-08-18 05:35 UTC, ananddeshpande1976 reviewed
How to contribute in this project

2022-08-22 11:45 UTC, SHADYKIMBUM commented
> Merge branch 'fix/basename-4' into 'development'

2022-09-01 19:53 UTC, Emanuelcarvalho2004 commented
Nice

2022-09-01 20:03 UTC, Emanuelcarvalho2004 commented
Nice 

> Hello good time in the browser Do you include the Persian language translator? There was more or less in the Pii Ke program, Search and Escape Please post here too. The number of Iranian users is not small Thank you

2022-09-01 20:03 UTC, Emanuelcarvalho2004 commented
Nice

2022-09-01 20:06 UTC, Emanuelcarvalho2004 commented
Nice 

> Hello good time in the browser Do you include the Persian language translator? There was more or less in the Pii Ke program, Search and Escape Please post here too. The number of Iranian users is not small Thank you

2022-09-01 20:06 UTC, Emanuelcarvalho2004 commented
Nice

2022-09-05 16:33 UTC, wawanar commented
kyc

2022-09-14 22:12 UTC, Mosesesmart requested changes
Thanks 🙏

2022-09-19 12:53 UTC, solbage approved these changes

2022-09-19 15:14 UTC, Thienan007 approved these changes
Ok

2022-09-19 15:18 UTC, Thienan007 approved these changes
Ok

2022-10-11 09:01 UTC, Theindra87 commented
Let't go..

Pada tanggal Sab, 13 Agt 2022 21.11, Asahan63 ***@***.***>
menulis:

> Go...
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/chatch/stellarexplorer/pull/331#issuecomment-1214165817>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AWVJ4ALGNBV5LZGG3OHYYD3VY6UIFANCNFSM5F4WB6YA>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***>
>

2022-10-28 07:49 UTC, nutty323 commented
Merge

2022-10-28 18:22 UTC, nutty323 commented
Merge branch fix

2022-11-09 13:30 UTC, nutty323 commented
Merge

2022-12-06 01:51 UTC, nutty323 commented
Merge branche/fix basename

2022-12-06 01:56 UTC, nutty323 commented
Megre/fix

2022-12-11 00:12 UTC, Itzjboy commented
So friends what do you say about this platform

2022-12-11 06:43 UTC, Mamatbat commented
Hi

2022-12-22 17:02 UTC, mrJambil1 commented
Good job 👍

2023-01-02 11:49 UTC, ZatmanOptionz24 commented
##í

2023-02-01 09:52 UTC, Costas1948 commented
Gpod

2023-03-05 05:48 UTC, minepicomosasrer00 commented
Thank you very much

2023-03-21 03:37 UTC, Fitra126 approved these changes
pi-apps:development

2023-03-22 07:44 UTC, Fitra126 approved these changes

2023-04-21 23:45 UTC, nanis94 reviewed
Dockerfile

2023-05-05 22:40 UTC, 09167372994 approved these changes

2023-05-05 22:44 UTC, 09167372994 approved these changes

2023-06-26 10:22 UTC, Capojazzy1 commented
Kyc no resolved till now why?

2023-06-26 10:27 UTC, Capojazzy1 commented
Approve all changes to real pi .

2023-06-26 10:35 UTC, Capojazzy1 commented
#331

2023-07-21 21:21 UTC, maripaungmai commented
{
  "_links": {
    "self": {
      "href": "https://api.testnet.minepi.com/ledgers/13125163"
    },
    "transactions": {
      "href": "https://api.testnet.minepi.com/ledgers/13125163/transactions{?cursor,limit,order}",
      "templated": true
    },
    "operations": {
      "href": "https://api.testnet.minepi.com/ledgers/13125163/operations{?cursor,limit,order}",
      "templated": true
    },
    "payments": {
      "href": "https://api.testnet.minepi.com/ledgers/13125163/payments{?cursor,limit,order}",
      "templated": true
    },
    "effects": {
      "href": "https://api.testnet.minepi.com/ledgers/13125163/effects{?cursor,limit,order}",
      "templated": true
    }
  },
  "id": "5dfdf63cd4477f63ffd8d1a6c76d891529515d852fd85b14dfa9a5978f98963e",
  "paging_token": "56372145839669248",
  "hash": "5dfdf63cd4477f63ffd8d1a6c76d891529515d852fd85b14dfa9a5978f98963e",
  "prev_hash": "a9636bfa20d0d0d1d1366585091f1cd2036d2aacd6ffdadd2317ca9ec88452f8",
  "sequence": 13125163,
  "successful_transaction_count": 15,
  "failed_transaction_count": 0,
  "operation_count": 15,
  "tx_set_operation_count": 15,
  "closed_at": "2023-07-21T21:19:28Z",
  "total_coins": "100000000000.0000000",
  "fee_pool": "2065756.6818620",
  "base_fee_in_stroops": 100000,
  "base_reserve_in_stroops": 100000000,
  "max_tx_set_size": 1000,
  "protocol_version": 15,
  "header_xdr": "AAAAD6lja/og0NDR0TZlhQkfHNIDbSqs1v/a3SMXyp7IhFL4Sly87VDaZODYILjJ3w4kbfzOIpyELXJjPOFkaIsTIY0AAAAAZLr2YAAAAAAAAAABAAAAAL0dIh9YCWKVtdZZd7HLMYRYlv5sCibPT1h2qqXnmjFeAAAAQBIwIrQ8ND/B9Ru2f66HYLNo/+TGd0GYSa/6bLB4pfh7jV1ktY8pbv3YQ0KKQkn//GC+mfzLkJiqnEKj7mFRfQVDpzCUkeYT7S7Q1NSMcXWlRv4CKvLoCw0Baozi/LFEK2ozXvMB5ZHrawoCwPVds8R+Btj6NV+USTpeMo/OKedgAMhGKw3gtrOnZAAAAAASybbuoTwAAAAAAAAAAAAEd0oAAYagBfXhAAAAA+g+qr+XlTRdNy9lrbxaE0+af0wwSStiyLBQLgHvgN6XtTs9isnuB91PdyBf57KJLEc11YfpdbDLj5Pq8FRWrHE+ra6IhywbYyBOzjkUXZA9SuO1oWb+ShTuaWwwULYDTw7jT60k40S6PT0u8/h4O3mmpzB9KtG7ZUOKo1vSLzNKngAAAAA="
}

2023-07-29 10:42 UTC, Camquyen1996 commented
https://sandbox.minepi.com/app/ng-c-linh-804cd7895c93abc4

2023-09-10 20:35 UTC, Steveai25 commented
Meeting with the reviewers

2023-09-23 19:02 UTC, Darknes990 commented
help me get pi

2023-09-23 21:52 UTC, Dauda080 commented
At what price are you buying it

On Sat, Sep 23, 2023, 8:02 PM Darknes990 ***@***.***> wrote:

> help me get pi
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/chatch/stellarexplorer/pull/331#issuecomment-1732388702>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AWCAHSL6LO7SWYV246SB3E3X34W4RANCNFSM5F4WB6YA>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***>
>

2023-10-03 21:06 UTC, Dezzj reviewed
Reviewed

2023-10-03 21:06 UTC, Dezzj reviewed
Veiwed

2023-10-04 02:58 UTC, chatch commented
not related to stellar explorer - only the pi fork ...

2023-10-04 02:58 UTC, closed without merging

2024-02-27 23:06 UTC, Asijoon commented
Hello, I was one of the pioneers of Pie, for some reason, the program was
deleted from my phone
Now I can't log in to my account
I corresponded several times, I tried very hard, but...
Please, if possible, help me log into my account










Your success is my wish

در تاریخ جمعه ۲ سپتامبر ۲۰۲۲،‏ ۰:۲۳ Emanuelcarvalho2004 <
***@***.***> نوشت:

> Nice
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/chatch/stellarexplorer/pull/331#issuecomment-1234714368>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AXO7MBLEOHDZS26INNAHMO3V4ECUJANCNFSM5F4WB6YA>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***>
>

2024-07-09 16:18 UTC, 301166 commented
Pi name Sauvos

2024-07-10 16:17 UTC, 301166 commented
Pi day is happy day!

2024-07-10 16:18 UTC, 301166 commented
All pi day is happy day!🙂

2024-10-14 13:45 UTC, Tysomi commented
Great day

2024-12-10 05:02 UTC, Sutherlandjoseph commented on src/components/Account.js
Nive

2025-05-03 01:46 UTC, TESLA-SATI commented
![LOGO](https://github.com/user-attachments/assets/fd24d88b-0065-4c5c-9ef4-8b66c2c36501)
SATI ; )